### ISSUE TITLE
Fetching properties dynamically from react itself in react-property

### ISSUE THREAD

**Issue by fabiospampinato** [remarkablemark/react-dom-core#13]
Would it be possible to remove the built-in hard-coded lists of properties and instead fetch them from react directly?

I'm asking this because react-property is a bit heavy, considering that most of its weight comes from structures internal to React that I'm bundling with the app already, so bundling the same thing twice doesn't seem great to me.

Plus my understanding is that the current lists are extracted from React v15, but what if I'm using React v17 or React v25 eventually, and that ships with more properties that react-property doesn't have hard-coded? react-property should be more future-proof ideally.

**Comment by remarkablemark** [comment]
That's a good question @fabiospampinato

Currently, `react-property` is using [scripts](https://github.com/remarkablemark/react-dom-core/tree/react-property%401.0.1/packages/react-property/scripts) to build the properties from `react-dom@15` so it's not exactly hard-coded.

The reason why we're using `react-dom@15` instead of a higher version is because the internal lib modules are no longer exposed in >15 (see #5).

To fetch the DOM/SVG properties from `react` will require a major rearchitecture in this project. It can be tricky because with the internals not exposed, how can we get the property configs? Are we going to clone the entire `react` repository and try to find the file? What if the file gets renamed or moved to a different directory? This adds a lot of upkeep and maintenance to this project.

Also, when you say that `react-property` is _heavy_, what do you consider heavy? Looking at the file size on [unpkg](https://unpkg.com/browse/react-property/), file files should be around ~10KB unminified.

If we build with webpack, the bundle is `8.34 KiB` minified:

```sh
$ npm i react-property webpack webpack-cli
$ echo "import 'react-property';" > index.js
$ npx webpack-cli ./index.js -o build
[webpack-cli] Compilation finished
asset main.js 8.34 KiB [emitted] [minimized] (name: main)
runtime modules 657 bytes 3 modules
cacheable modules 13.2 KiB
  modules by path ./node_modules/react-property/lib/*.js 9.92 KiB
    ./node_modules/react-property/lib/HTMLDOMPropertyConfig.js 2.5 KiB [built] [code generated]
    ./node_modules/react-property/lib/SVGDOMPropertyConfig.js 7.26 KiB [built] [code generated]
    ./node_modules/react-property/lib/injection.js 163 bytes [built] [code generated]
  ./index.js 25 bytes [built] [code generated]
  ./node_modules/react-property/index.js 3.24 KiB [built] [code generated]
webpack 5.2.0 compiled successfully in 522 ms
```

**Comment by fabiospampinato** [comment]
> To fetch the DOM/SVG properties from react will require a major rearchitecture in this project. It can be tricky because with the internals not exposed, how can we get the property configs? Are we going to clone the entire react repository and try to find the file? What if the file gets renamed or moved to a different directory? This adds a lot of upkeep and maintenance to this project.

It would seem some manual work would be required indeed 🤔 Finding where those lists are located should be easy, we can just search for some obscure attribute and we'll likely find the file listing them right away, keeping the lists up-to-date could be tricky though, not having an up-to-date list on the other hand makes the library not see the full picture.

> Also, when you say that react-property is heavy, what do you consider heavy? Looking at the file size on unpkg, file files should be around ~10KB unminified.

> If we build with webpack, the bundle is 8.34 KiB minified:

I said "a bit heavy", what I mean by heavy is that something weighs significantly more than it should for a purpose, like a 1kb JS function that sums two integers would be heavy even though it's just 1kb in size. react-property's heaviness, from my perspective where I only need it to help me build a react component from some HTML, comes from providing some redundant information for my needs (camel-cased and kebab-cased variants don't need to be both listed as one can be computed from the other, non-boolean attributes that are identical when camel-cased and kebab-cased are useless to even mention to me), basically I'm just saying for my particular need the size of the library could be shrunk down a bit, maybe 1kb~4kb or something.

As it doesn't seem possible to extract the list from an instance of react itself I'm closing this issue.
