### ISSUE TITLE
Can we upgrade to react-dom@^16

### ISSUE THREAD

**Issue by mark-casias** [remarkablemark/react-dom-core#5]
There are some packages that require this package, which makes hooks not work with them. Wondering if we can update to "react-dom": "^16",

**Comment by remarkablemark** [comment]
So I provided some context in remarkablemark/html-react-parser#105.

The reason this package depends on `react-dom@15` is because in 16, the internal lib modules are no longer exposed. For some projects that depend on them, this package is a way to install both `react-dom@latest` and `react-dom@15`.

**Comment by remarkablemark** [comment]
Closing issue given that remarkablemark/html-react-parser#105 has been resolved
